### ISSUE TITLE
Error in _framework folder location

### ISSUE THREAD

**Issue by arturohernandez10** [Elringus/DotNetJS#16]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "PublishDotNetJS" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '...\bin\Release\net6.0\publish\wwwroot\_framework'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at DotNetJS.Packer.ProjectMetadata.LoadAssemblies(String directory)
   at DotNetJS.Packer.PublishDotNetJS.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	vNextDashboard.Pathways		0	

The folder is not:
     ....\bin\Release\net6.0\publish\wwwroot\_framework
It's 
    ...\bin\Release\net6.0\wwwroot\_framework
    
I have not found a place to set a different location.

**Comment by Elringus** [comment]
`net6.0\wwwroot_framework` is not the publish dir we need, it's a temporary location. 

`net6.0\publish\wwwroot_framework` is the correct location. Check the sample projects or tests, they all work with that location.
